version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: testdatabase
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '1000:5432'
